// other/udemiCourses/React/React-pro/4-redux/src/components/counter.jsx
import React from 'react'
import { connect } from 'react-redux'
const Counter = ({counter, inc, dec}) => {
    return (
        <div>
            <h2 id="counter">{counter}</h2>
            <button id="dec" onClick={dec}>-</button>
            <button id="inc" onClick={inc}>+</button>
        </div>
    )
};

const mapStateToProps = (state) => {
    return {
        counter: state
    }
}

export default connect(mapStateToProps)(Counter)

// other/laracast-courses/testingVue/lesson-3/src/components/Counter.vue
<template>
    <div>
        <span class="count" v-text="count"></span>
        <button @click="count++" class="inc">Increment</button>
        <button @click="count--" class="dec">Increment</button>
    </div>
</template>

<script>
	export default {
		data () {
			return {
				count: 0
			};
		}
	}
</script>
